"""empty message

Revision ID: 28e2cb33ddf1
Revises: 6c96252c3ebb
Create Date: 2018-11-09 11:23:22.308545

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28e2cb33ddf1"
down_revision = "6c96252c3ebb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("location_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("hashed_authorisation_code", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("hashed_authorisation_code"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device")
    # ### end Alembic commands ###
