"""drop tinyurl suffix

Revision ID: 80154c6d2d2a
Revises: a3b687d03b98
Create Date: 2020-05-19 13:01:49.138876

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80154c6d2d2a"
down_revision = "a3b687d03b98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_clinician_clinician_id"), "clinician", ["clinician_id"], unique=True
    )
    op.drop_constraint("clinician_clinician_id_key", "clinician", type_="unique")
    op.drop_index("clinician_id", table_name="clinician")
    op.drop_index("patient_id", table_name="patient")
    op.create_index(
        op.f("ix_patient_activation_code"), "patient_activation", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_patient_activation_patient_id"),
        "patient_activation",
        ["patient_id"],
        unique=False,
    )
    op.drop_index("activation_code", table_name="patient_activation")
    op.drop_column("patient_activation", "tinyurl_suffix")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patient_activation",
        sa.Column(
            "tinyurl_suffix", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.create_index("activation_code", "patient_activation", ["code"], unique=True)
    op.drop_index(
        op.f("ix_patient_activation_patient_id"), table_name="patient_activation"
    )
    op.drop_index(op.f("ix_patient_activation_code"), table_name="patient_activation")
    op.create_index("patient_id", "patient", ["patient_id"], unique=True)
    op.create_index("clinician_id", "clinician", ["clinician_id"], unique=True)
    op.create_unique_constraint(
        "clinician_clinician_id_key", "clinician", ["clinician_id"]
    )
    op.drop_index(op.f("ix_clinician_clinician_id"), table_name="clinician")
    # ### end Alembic commands ###
