"""empty message

Revision ID: 82e4ae6c4644
Revises: 28e2cb33ddf1
Create Date: 2018-11-09 16:08:52.087359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "82e4ae6c4644"
down_revision = "28e2cb33ddf1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_activation",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=36), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("attempts_count", sa.SmallInteger(), nullable=False),
        sa.Column("activated_timestamp", sa.DateTime(), nullable=True),
        sa.Column("activated_timezone", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.uuid"], ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.rename_table("activation", "patient_activation")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("patient_activation", "activation")
    op.drop_table("device_activation")
    # ### end Alembic commands ###
