"""empty message

Revision ID: a5ba7214ea2a
Revises: 
Create Date: 2018-03-08 14:05:20.288187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5ba7214ea2a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("email_address", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email_address"),
        sa.UniqueConstraint("patient_id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "activation",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=36), nullable=False),
        sa.Column("otp", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["user.patient_id"]),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activation")
    op.drop_table("user")
    # ### end Alembic commands ###
