"""empty message

Revision ID: ba93cab856a0
Revises: a5ba7214ea2a
Create Date: 2018-03-08 15:07:11.690783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba93cab856a0"
down_revision = "a5ba7214ea2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activation", sa.Column("tinyurl_suffix", sa.String(length=10), nullable=False)
    )
    op.add_column("activation", sa.Column("used", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activation", "used")
    op.drop_column("activation", "tinyurl_suffix")
    # ### end Alembic commands ###
