"""empty message

Revision ID: cf267146d799
Revises: e242ed5b58fd
Create Date: 2018-07-30 10:50:14.381976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf267146d799"
down_revision = "e242ed5b58fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activation", sa.Column("activated_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "activation", sa.Column("activated_timezone", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activation", "activated_timezone")
    op.drop_column("activation", "activated_timestamp")
    # ### end Alembic commands ###
