"""empty message

Revision ID: f630f7951d5e
Revises: 569b95c34f29
Create Date: 2018-11-13 14:07:37.424270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f630f7951d5e"
down_revision = "569b95c34f29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("device", sa.Column("authorisation_code_salt", sa.String(), nullable=True))
    op.alter_column("device", "hashed_authorisation_code", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint("device_auth_code_salt", "device", ["authorisation_code_salt"])
    op.drop_column("device_activation", "attempts_count")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device_activation",
        sa.Column(
            "attempts_count",
            sa.SMALLINT(),
            autoincrement=False,
            nullable=False,
            default=0,
        ),
    )
    op.drop_constraint("device_auth_code_salt", "device", type_="unique")
    op.alter_column("device", "hashed_authorisation_code", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("device", "authorisation_code_salt")
    # ### end Alembic commands ###
