@startuml

skinparam defaultFontName Courier

Class Clinician {
    VARCHAR[36]         ★ uuid                     
    VARCHAR[36]         ⚪ clinician_id             
    DATE                ⚪ contract_expiry_eod_date_
    DATETIME            ⚪ created                  
    VARCHAR             ⚪ created_by_              
    BOOLEAN             ⚪ login_active             
    DATETIME            ⚪ modified                 
    VARCHAR             ⚪ modified_by_             
    VARCHAR[50]         ⚪ send_entry_identifier    
    +                   groups                     
    +                   products                   
    INDEX[clinician_id] » ix_clinician_clinician_id
}

Class Device {
    VARCHAR[36] ★ uuid                     
    BOOLEAN     ⚪ active                   
    VARCHAR     ⚪ authorisation_code_salt  
    DATETIME    ⚪ created                  
    VARCHAR     ⚪ created_by_              
    VARCHAR     ⚪ description              
    BLOB        ⚪ hashed_authorisation_code
    VARCHAR     ⚪ location_id              
    DATETIME    ⚪ modified                 
    VARCHAR     ⚪ modified_by_             
    +           activation                 
    to_dict()                              
}

Class DeviceActivation {
    VARCHAR[36]               ★ uuid               
    VARCHAR[36]               ☆ device_id          
    DATETIME                  ⚪ activated_timestamp
    INTEGER                   ⚪ activated_timezone 
    VARCHAR[36]               ⚪ code               
    DATETIME                  ⚪ created            
    VARCHAR                   ⚪ created_by_        
    DATETIME                  ⚪ modified           
    VARCHAR                   ⚪ modified_by_       
    BOOLEAN                   ⚪ used               
    +                         device               
    get_activated_timestamp()                      
}

Class Group {
    VARCHAR[36] ★ uuid        
    DATETIME    ⚪ created     
    VARCHAR     ⚪ created_by_ 
    DATETIME    ⚪ modified    
    VARCHAR     ⚪ modified_by_
    VARCHAR[20] ⚪ name        
    +           clinicians    
}

Class Patient {
    VARCHAR[36] ★ uuid                     
    VARCHAR     ⚪ authorisation_code_salt  
    DATETIME    ⚪ created                  
    VARCHAR     ⚪ created_by_              
    VARCHAR     ⚪ email_address            
    BLOB        ⚪ hashed_authorisation_code
    DATETIME    ⚪ modified                 
    VARCHAR     ⚪ modified_by_             
    VARCHAR[36] ⚪ patient_id               
    VARCHAR     ⚪ phone_number             
    +           activation                 
    to_dict()                              
}

Class PatientActivation {
    VARCHAR[36]               ★ uuid                            
    VARCHAR[36]               ☆ patient_id                      
    DATETIME                  ⚪ activated_timestamp             
    INTEGER                   ⚪ activated_timezone              
    SMALLINT                  ⚪ attempts_count                  
    VARCHAR[36]               ⚪ code                            
    DATETIME                  ⚪ created                         
    VARCHAR                   ⚪ created_by_                     
    BLOB                      ⚪ hashed_otp                      
    DATETIME                  ⚪ modified                        
    VARCHAR                   ⚪ modified_by_                    
    VARCHAR                   ⚪ otp_salt                        
    BOOLEAN                   ⚪ used                            
    +                         patient                           
    get_activated_timestamp()                                   
    to_dict()                                                   
    INDEX[code]               » ix_patient_activation_code      
    INDEX[patient_id]         » ix_patient_activation_patient_id
}

Class Product {
    VARCHAR[36] ★ uuid        
    DATETIME    ⚪ created     
    VARCHAR     ⚪ created_by_ 
    DATETIME    ⚪ modified    
    VARCHAR     ⚪ modified_by_
    VARCHAR[20] ⚪ name        
    +           clinicians    
}

DeviceActivation <--o Device: device_id

PatientActivation <--o Patient: patient_id

right footer generated by sadisplay v0.4.9

@enduml
